### ISSUE TITLE
createLocation error used on server side for universal app

### ISSUE THREAD

**Issue by michaelBenin** [mjackson/history#263]
Today I'm upgrading to the latest history in my app. 

My old code which still works with latest react router is as so:

```
import createLocation from 'history/lib/createLocation';

const location = createLocation(req.url);
match({routes, location}, (error, redirectLocation, renderProps) =>  {
  // logic here to send rendered dom from server
  }
```

The code that breaks when upgrading:
```
import { createLocation } from 'history';

const history = createLocation(req.url);
  match({routes, history}, (error, redirectLocation, renderProps) => {
    // logic here to send rendered dom from server
}
```

I'm following from these docs:
https://github.com/mjackson/history/blob/master/docs/Location.md

Stacktrace:

```
TypeError: history.listen is not a function
    at match (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/react-router/lib/match.js:56:24)
    at exports.default (server/middleware/react_router_middleware.js:15:3)
    at Layer.handle [as handle_request] (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:312:13)
    at /Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:271:10)
    at /Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express-bunyan-logger/index.js:156:9
    at /Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express-bunyan-logger/index.js:10:9
    at Layer.handle [as handle_request] (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:312:13)
    at /Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:271:10)
    at /Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:618:15
    at next (/Users/mbenin/Desktop/react-ssr-boilerplate/node_modules/express/lib/router/index.js:256:14)
```

**Comment by michaelBenin** [comment]
Changing the variable name from history to location fixed this. 

Getting a new warning but the bug is fixed.

**Comment by michaelBenin** [comment]
This warning could be better:

```
Warning: [history] Using createLocation without a history instance is deprecated; please use history.createLocation instead
```
I don't think I can create a history instance on the server though. Debugging.

**Comment by taion** [comment]
1. This isn't the right repo.
2. There's a guide on server side rendering – please follow that.

**Comment by michaelBenin** [comment]
@taion I'm following the server side rendering from react router. 

Are you sure that this isn't the right repo? I'm following this doc as stated above:

https://github.com/mjackson/history/blob/master/docs/Location.md

This method should work in a server side environment.

**Comment by michaelBenin** [comment]
@taion apologies, refactored to fix:

```
match({ routes, location: req.url }
```

I thought it's worth it to mention that the above creating a history instance on the server isn't supported as well as making those calls on the server gives warnings that are relevant for the browser.

**Comment by taion** [comment]
It's not entirely that straightforward. The full semantics are a bit more complicated than that, but possibly not of much practical use – for now, it's best to just follow the pattern in the guide.

**Comment by michaelBenin** [comment]
Anyone else seeing this issue, this is related: 

https://github.com/reactjs/react-router-redux/blob/master/examples/server/server.js

See createMemoryHistory:
```
import { createMemoryHistory, match, RouterContext } from 'react-router'
```

Thank you for taking the time taion.

**Comment by koistya** [comment]
Q: How do you think, is it OK to initialize a new instance of the "history" module during server-side rendering (SSR) for each HTTP request, or is it better to handle redirects and stuff like that without using "history" ([example](https://github.com/kriasoft/react-starter-kit/pull/879))?
